### ISSUE TITLE
Add optional parameter to specify head movement position  and height offset

### ISSUE THREAD

**Issue by Nesciosquid** [aparolfe/pause-gcode#1]
An alternative to this is to have the user provide a config file that the script checks when run, where you can specify the offset height, XY position, etc.

Add arguments for x,y,z (offset), and output file name.

**Comment by aparolfe** [comment]
Should we enforce any/all of these to be positive? I'm assuming the zOffset at least should be positive?

**Comment by aparolfe** [comment]
Implemented (no checking for positive numbers because they might be negative for some systems)
